### ISSUE TITLE
Find a diffrent provider that Git LFS.  LFS is not free on GitHub

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#108]
Git LFS is not free on GitHub.  Why we used it is because the files are too large to be accepted as part of the git repo itself.

However, GitHub LFS sucks when it comes to good usage metrics.  I've already paid for 100 GB so far.

Suggestions?

**Comment by tomrtk** [comment]
I believe it is due to actions? Pulling for each run of tests etc.

Is it possible to cache the models and not use `lfs` in the workflows?

**Comment by MindTooth** [comment]
Seems others have the same problem[1].  Caching would really be one way to go.  At least as a remedy before something permanent.


[1]: https://www.develer.com/en/avoiding-git-lfs-bandiwdth-waste-with-github-and-circleci/

**Comment by MindTooth** [comment]
Example to try. https://github.com/actions/checkout/issues/165#issuecomment-657673315
