### ISSUE TITLE
Place config file in correct location on mac systems

### ISSUE THREAD

**Issue by Kad1n** [tomrtk/fish-code#112]
Maybe look at using `platform.system()`. https://stackoverflow.com/a/58071295.  Then we’ll have support for mac too.

Suggestion: https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

_Seems that the original version of this vanished._

_Originally posted by @MindTooth in https://github.com/MindTooth/fish-code/pull/73#discussion_r671450464_

**Comment by MindTooth** [comment]
I want to look into using https://github.com/dynaconf/dynaconf for config management.

@tomrtk a solution that would fit?

Ed1t: maybe not. https://github.com/dynaconf/dynaconf/issues/73#issuecomment-691396022

Ed2t: https://github.com/platformdirs/platformdirs

**Comment by tomrtk** [comment]
> I want to look into using https://github.com/dynaconf/dynaconf for config management.
> 
> @tomrtk a solution that would fit?
> 
> Ed1t: maybe not. [dynaconf/dynaconf#73 (comment)](https://github.com/dynaconf/dynaconf/issues/73#issuecomment-691396022)
> 
> Ed2t: https://github.com/platformdirs/platformdirs

Look like you have found one solution. alternative could be using `platform` and construct the paths our self as is done today in `config`. I am open to both.

**Comment by MindTooth** [comment]
I like to at least try to implement something using both.  Having XDG and Windows path handling is great.
