### ISSUE TITLE
Integration test fails randomly in ci runs

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#129]
For some reason unbeknown to me, the integration test fails from time to time. See the following [run](https://github.com/MindTooth/fish-code/runs/3134354844?check_suite_focus=true).

From what I can gather, it seems to crash on reading JSON data supplied from requests.  But also complains about something SQLAlchemy related too.  Initial thought, is that they are related.

**Comment by ProdigSun** [comment]
I tried to see which tests failed but couldn't. Will try again later. However, after inspecting some tests, I saw that some tests have timers for waiting a certain endpoint becoming reacheable. From my experience, this could cause trouble If the machine on the cloud is randomly slow. Did you try increasing the timers/retries? :)

**Comment by tomrtk** [comment]
Looks like it could be the spin wait loop condition that causes this.
https://github.com/MindTooth/fish-code/blob/cb558c3cc1101c7722f134bcb19ec3e85020415c/tests/integration/test_services.py#L67

If the response is not a valid response it still tires to convert it to json, thereby the `JSONDecodeError`. Should probably also use the get function on the resulting dictionary with a default value to avoid a `KeyError` if the response do not contain the key `_status`.

Something like this maybe:

```python
status = ""
while status != "Done":
    logger.info("Waiting for job to finish.")
    time.sleep(5)
    res = requests.get(url):
    
    try:
	status = res.json().get("_status", "")
    except JSONDecodeError as e:
    	logger.warning(f"Response not valid json, error: {repr(e)}, response: {repr(res)}")
    	continue
```

In addition maybe a max number of retries check.

**Comment by MindTooth** [comment]
[Another one](https://github.com/MindTooth/fish-code/runs/3161896899?check_suite_focus=true).

**Comment by ProdigSun** [comment]
From the logs in sonar: 
```            
 response = client.get(
                "/projects/1/jobs/1/csv",
                follow_redirects=True,
            )
>           assert response.status_code == 200
E           assert 500 == 200
E            +  where 500 = <Response streamed [500 INTERNAL SERVER ERROR]>.status_code
```
Did you check if this endpoint is working properly?

**Comment by Kad1n** [comment]
You might get a 500 internal server error if for some reason a thread or process crashes. The output of which might not be captured by pytest. I suspect it might have something to do with the preview API call just before the block with an error. What happens if you try to call on the API when it's currently busy handling a preview?

**Comment by MindTooth** [comment]
With Flask acting as a middleware and is not asynchronous, maybe we are seeing limits reached?

**Comment by MindTooth** [comment]
I hope #143 have fixed both now.

**Comment by MindTooth** [comment]
Seems the CSV error is back. 😭  By the looks of it, it's maybe related to threading.

Ref.: https://github.com/MindTooth/fish-code/runs/3269670951?check_suite_focus=true
