### ISSUE TITLE
Update user docs

### ISSUE THREAD

**Issue by R0flcopt3r** [tomrtk/fish-code#188]
We need better installation instructions. The biggest problem is the lack of linux installation instructions.

We should also find a way to update the URLs for the wheel when a new version is released, or explain better how the user can figure that part out.

**Comment by tomrtk** [comment]
> ... or explain better how the user can figure that part out.

I feel it is not to bad in the documentation, but maybe point out extra that the command with a url is only a example.

If this is a big issue, it would be better to get it released to `pypi`, instead of getting some automation to update the user docs url.
