### ISSUE TITLE
Pick a license for the project

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#24]
The project needs an open-source license for us to open it for the public.

No definite license was picked in the thesis.  From looking at the existing [NINA-org](https://github.com/ninanor).  We can see that many projects are using some version of the GPL license.  I personally feel that we should follow suit.  However, which one for us to choose is up for discussion.

My thoughts would drift towards AGPL simply because it should stay open-source and hopefully be developed by future bachelor groups.  As in this being more of an academic solution that a governmental organization has commissioned.

**Comment by tomrtk** [comment]
Need to keep in mind that AGPLv3 is not compatible with GPLv2.

**Comment by MindTooth** [comment]
Fixed by https://github.com/MindTooth/fish-code/pull/30.
