### ISSUE TITLE
Refresh the start job button until job is complete

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#242]
Currently one needs to manually refresh the page to see the status of the job.  This can be a bit tad annoying.

--

Suggestion for solving this is looking at using some JavaScript to automatically run a get status and refresh accordingly.  A background process of some sort.  However, this should only run as long as the job is not completed and still running.

[Possible solution](https://www.sitepoint.com/community/t/refresh-a-div-every-5-mins/23513/7).

**Comment by R0flcopt3r** [comment]
I agree, and that solution is perfectly fine.

**Comment by MindTooth** [comment]
Another [source](https://stackoverflow.com/questions/109086/stop-setinterval-call-in-javascript).

**Comment by MindTooth** [comment]
Closed in favor of https://github.com/tomrtk/fish-code/issues/104.
