### ISSUE TITLE
Hack: use v1.0.0 release to download model

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#442]
Seeing that we always end up using the LFS quota, I figured we could perhaps try to cheat the system by attaching them inside the v1.0.0 release and download them from there.

Release: https://github.com/MindTooth/fish-code/releases/tag/v1.0.0

---

Possible step:

1. Download using `urllib.request`: https://www.simplifiedpython.net/python-download-file/#urllibrequest_Module
2. But, where to store the temporary model when it's downloaded, and how to refer to it later. 🤔 
3. Beat the LFS quota, eq. win. 🥳 

---

Thoughts on possible solutions for the download and/or other way of doing this?

**Comment by MindTooth** [comment]
I belive it's this sections that we need to tweak: https://github.com/MindTooth/fish-code/blob/5ea3093525a441cce157989bd832139f31fe6659/src/detection/api.py#L23-L26

**Comment by R0flcopt3r** [comment]
For storing the weights we could use `(/var/cache|$XDG_CACHE_HOME)/nina` if we say this is a temporary file that we don't care about[1]. I think this is the best option. It can be deleted whenever, and it's not up to the program to clean it when uninstalling in my opinion.

Could also fit in either `/var/lib/nina`[2] or `/usr/lib/nina`[3]. The latter means it should be possible to have the file read only, I assume we can. `$XDG_DATA_HOME/nina` and `$XDG_STATE_HOME/nina` are their respective freedesktop home locations. I do feel like we would need to be able to clean up these locations when removing the program, and I don't know if we have the option to do so. Obviously deleting a venv with the software would not let us do any cleanup, and I think this is the "default" way to uninstall. It is at least by me.. 😅 

[1] : https://www.pathname.com/fhs/pub/fhs-2.3.html#VARCACHEAPPLICATIONCACHEDATA
[2]: https://www.pathname.com/fhs/pub/fhs-2.3.html#VARLIBVARIABLESTATEINFORMATION
[3]: https://www.pathname.com/fhs/pub/fhs-2.3.html#USRLIBLIBRARIESFORPROGRAMMINGANDPA

**Comment by tomrtk** [comment]
I believe the weights within the wheel that is used at runtime. 

It should be possible to `unzip` the `.whl` and get it that way as well in the runner -- as long as we could copy the weights to correct location in git structure, it should work on the runner. 

A way to test it could be to remove the weights from the folder `src/detection/weights`, but keeping the folder in a test branch. The in the actions remove LFS and copy the weights to that location with something like:
```sh
wget -P ./src/detection/weights https://github.com/MindTooth/fish-code/releases/download/v1.0.0/yolov5s-imgsize-640.pt
# do same for other
```
----
I think we only need to change how the action works, but I do not remember exactly how github actions clone the repository.

**Comment by tomrtk** [comment]
if this is changes, it need to be updated in the package workflow as well, so the weights is present when the `whl` is built.

**Comment by MindTooth** [comment]
I’m paying for traffic as a temporary solution.  Only $5 each month.
