### ISSUE TITLE
2. Move stats calculation to core

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#54]
Currently, the job statistics are calculated in `ui`.  But that only works on the data pullet.  When implementing a form of pagination, this will not provide a consistent result.

Since we want all stats about a job regardless of how many objects, etc. we pull, the stats should be on the job itself.  Logically this should be an endpoint provided by `core` when pulling a job.

**Comment by R0flcopt3r** [comment]
Something like this for making the stats.

```py
class Job
{...}
    @property
    def get_stats(self):
        stats = Dict()
        stats["total_count"] = len(self._objects)

        for o in self._objects:
            if o.label not in stats:
                stats[o.label] = 0
            stats[o.label] = +1
        return stats
```
