### ISSUE TITLE
1. Generate route for getting filesystem - core

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#57]

**Comment by tomrtk** [comment]
Ref #38.

Flow:
- Endpoint: `/storage/` takes argument of path to get files and folders of.
- api -> services (generate jstree structure of current path).

**Comment by MindTooth** [comment]
How jsTree works when attempting at going for a lazy load approach is that the nodes are loading by sending a request to an endpoint with the `id`-parameter.

So, when jsTree loads, it will send a request to the endpoint with `#` as a parameter.  `#` here means the root folder.  When opening children, it will then sends a new request with the child's ID as the parameter.

Ref.: https://github.com/vakata/jstree/blob/9daa44eb0de0c0808b1b13871c5b0a647ca2d7f6/demo/sitebrowser/index.php#L112

<blockquote><img src="https://opengraph.githubassets.com/0c05c63b1e7ac0cc46b54e93b40544e881dea493895c8f9665339502394d3078/vakata/jstree" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/vakata/jstree">vakata/jstree</a></strong></div><div>jquery tree plugin. Contribute to vakata/jstree development by creating an account on GitHub.</div></blockquote>

**Comment by MindTooth** [comment]
A possible addition to the endpoint is for not sending a populated children list but instead set it to true.  This makes jsTree render the node as a folder that is possible to open.  When opening said folder a new request will be sent with a flag to get the children as well.

This is only an extra if time permits.
