### ISSUE TITLE
2. Paginate objects result table inside job - ui

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#60]

**Comment by R0flcopt3r** [comment]
Something like this for making the stats.

```py
class job
{...}
    @property
    def get_stats(self):
        stats = Dict()
        stats["total_count"] = len(self._objects)

        for o in self._objects:
            if o.label not in stats:
                stats[o.label] = 0
            stats[o.label] = +1
        return stats
```

**Comment by R0flcopt3r** [comment]
suggestion for endpoint for getting objects

```py
@core_api.get(
    "/projects/{project_id}/jobs/{job_id}/objects", response_model=schema.Object
)
def get_objects_from_job():
    pass
```

**Comment by tomrtk** [comment]
Start looking into using https://datatables.net/ to paginate table of objects.

<blockquote><img src="/media/images/favicon.png" width="48" align="right"><div><strong><a href="https://datatables.net/">DataTables | Table plug-in for jQuery</a></strong></div></blockquote>

**Comment by tomrtk** [comment]
Depending some on #61. 

Currently in  4fdee2f, implemented `api client` with expected data from `core api` and route in `project` returning mocked data to test ui. Currently the preview 'popup' is not working.
