### ISSUE TITLE
2. Route for getting objects with pagination - core

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#61]

**Comment by tomrtk** [comment]
> suggestion for endpoint for getting objects
> 
> ```python
> @core_api.get(
>     "/projects/{project_id}/jobs/{job_id}/objects", response_model=schema.Object
> )
> def get_objects_from_job():
>     pass
> ```
> 
> This aligns with the convention otherwise used for project and job.

**Comment by tomrtk** [comment]
Endpoint should return following metadata:
- Total count of objects in job

Ideal the endpoint should take a `start` and `length` argument. Where start is the object to be the first in response and length is the number of objects to be returned, eg. `job.objects[start:start + lenght]`
