### ISSUE TITLE
Let core create jsTree structure for permission denied

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#615]
Today we send an HTTP error code to jsTree, and it does some magic to disable a node if permission problems.  However, I suggest that this should be handled in the API by adding the following fields:

```json
  "icon" : "bi bi-x-circle"
  "state" : {
    "disabled"  : "disabled" 
  }
```

By doing this, there is no need for Flask or jsTree to handle 403.  `/storage` is today only serving jsTree anyway.  Though, Flask need to handle if root is 403 I guess.

jsTree won't offer the option to open a node if it's disabled I hope.  If then a folder is forbidden and have the options added to it as above example, this should stop any future navigation to that subtree.

This change will be in: https://github.com/tomrtk/fish-code/blob/06d4bfda56026dc3c6d54d2b0a2aeb4690afae75/src/core/services.py#L626 

---

I'm cleaning some JavaScript in #607 and noticed this extra steps.  This will save parsing in:
https://github.com/tomrtk/fish-code/blob/06d4bfda56026dc3c6d54d2b0a2aeb4690afae75/src/ui/src/js/jstree.js#L29-L33

@tomrtk any comments?

**Comment by tomrtk** [comment]
First thought,  do `get_directory_listing` then also need to check each of the files/folders in path for permission?  unsure if it would result in a larger overhead

The core api should probably regardless of the above changes, check the given path for permission errors and return a error if issues, as the api can be called directly.

**Comment by MindTooth** [comment]
I guess this play into https://github.com/tomrtk/fish-code/issues/38.  I'm all for trying to make it as performant as possible.

One improvement could perhaps that we could ignore dotfiles.  They are usually hidden.  That would return fewer hits.

To play out how jsTree would work:

1. Show the root tree opened
    1. Folder with a tick, if children
    2. Files
    2. Either show disabled on files and/or folder
2. Select file(s) and/or open another folder

So, 1 iii. could show status, or this could be perhaps updated when someone tries to select/open.  But, I'm not sure what's more expensive.  Give the full tree w/ status, or send a request for each action.

For 2, one could perhaps not show permission denied for folders, but rather get this when attempting to open.  Which, I perhaps is what happening today.  Long time since we've implemented this. 😅 

---

The behavior have always been to just show a list.  Perhaps we can improve it on both sides.

I also want to do some tweaks regarding the icons being used.  We already include https://icons.getbootstrap.com/?q=folder and could use that too.

**Comment by tomrtk** [comment]
> I guess this play into https://github.com/tomrtk/fish-code/issues/38. I'm all for trying to make it as performant as possible.

I guess that issue should be closed, as it is how it was done first when it was done in `ui`. today it only loads content of one folder at the time.

> Give the full tree w/ status, or send a request for each action.

I think what we did first, to give the full tree recursively is more expensive, as illustrated in #38.

if only looking at the time generating the json structure, it should be easy to check the new implementation compared to existing as in the issue above.

**Comment by tomrtk** [comment]
did miss the 'w/ status' in your response. I would give it a test to see how much time it adds to populate the status for the current folder. as long as it is not of many magnitudes slower I guess it is ok.
