### ISSUE TITLE
Update Makefile & documentation to reflect recent changes

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#65]
Recent changes made by #50 were not added to the Makefile.

Changes:

* `pip install -e .[dev,testing]`
* More incline to use `venv` instead of `.venv`
* Be more specific about steps

Other
https://bugs.python.org/issue38927

* `--upgrade-deps` is only available Python >= 3.9  https://docs.python.org/3/library/venv.html#module-venv

**Comment by R0flcopt3r** [comment]
Why do you want `venv` over `.venv`? in my eyes it just adds more noise, it's a folder you'll never interact with.

Which steps do you think should be more specific?

**Comment by MindTooth** [comment]
> Why do you want `venv` over `.venv`? in my eyes it just adds more noise, it's a folder you'll never interact with.
I would argue the other way around, that you then actually see that you have a venv folder straight away.  Nothing is hidden away that you need to debug why.

> Which steps do you think should be more specific?

I guess more verbose what each section does.  E.g. `git-lfs` is a hard requirement.  Ant other nits.

**Comment by R0flcopt3r** [comment]
> > Why do you want `venv` over `.venv`? in my eyes it just adds more noise, it's a folder you'll never interact with.
> > I would argue the other way around, that you then actually see that you have a venv folder straight away.  Nothing is hidden away that you need to debug why.
> 
> > Which steps do you think should be more specific?
> 
> I guess more verbose what each section does. E.g. `git-lfs` is a hard requirement. Ant other nits.

so, we're looking at two different issues here. Makefile being broken, and readme overall being bad?

**Comment by MindTooth** [comment]
Yes.

**Comment by tomrtk** [comment]
#553
