### ISSUE TITLE
Objects from other jobs showing in job view.

### ISSUE THREAD

**Issue by tomrtk** [tomrtk/fish-code#81]
Reproduce:
On master(b61eb90c0) run two jobs in a project.
Objects from the fist job shows up in the second job as in image below.

![image](https://user-images.githubusercontent.com/43438127/124883058-4133ba00-dfd1-11eb-9a4b-37e7d194d9bd.png)

**Comment by R0flcopt3r** [comment]
iirc, you have to queue the job before the first one is done.
